version: '2.0'

services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=pass123
     - POSTGRES_USER=jnoma
     - POSTGRES_DB=liske_db
    ports:
     - 5432:5432
    volumes:
     - /var/snap/docker/common/var-lib-docker/volumes/liske-db-vol/_data
